spring.application.name=MovieDetails
server.port=8082

# Movie Service
movie.service.base-url=http://localhost:8080/movie/movie

# Movie Review Service
review.service.base-url=http://localhost:8081/review/movie